name: Linux

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library_type: [static, shared]
        include:
          - library_type: static
            preset: linux
            description: "Static Library"
          - library_type: shared
            preset: linux-shared
            description: "Shared Library"

    name: Build (${{ matrix.description }})

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.2"
          host: linux
          target: desktop
          arch: linux_gcc_64

      - name: Build the library (${{ matrix.description }})
        run: |
          cmake --preset ${{ matrix.preset }} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
          cmake --build --preset ${{ matrix.preset }} --target install
