name: Windows

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        library_type: [static, shared]
        include:
          - library_type: static
            preset: windows-ci
            description: "Static Library"
          - library_type: shared
            preset: windows-ci-shared
            description: "Shared Library"

    name: Build (${{ matrix.description }})

    steps:
      - name: Check Out
        uses: actions/checkout@v7

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.3"
          host: windows
          target: desktop
          arch: win64_msvc2022_64

      - name: Build the library (${{ matrix.description }})
        run: |
          cmake --preset ${{ matrix.preset }} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_PREFIX_PATH="$env:QT_ROOT_DIR"
          cmake --build --preset ${{ matrix.preset }} --target qlementine

      - name: Build the Qt style plugin (${{ matrix.description }})
        run: cmake --build --preset ${{ matrix.preset }} --target qlementinestyleplugin

      - name: Install the library and plugin (${{ matrix.description }})
        run: cmake --build --preset ${{ matrix.preset }} --target install

      - name: Build the Sandbox app.
        if: matrix.library_type == 'static'
        run: cmake --build --preset windows-ci-sandbox
